module.exports = [
    {
        id: "20sim",
        displayName: "20-sim",
        homepage: "http://www.20sim.com/",
        email: "undefined",
        note: "Modeling and simulation program for mechatronic systems and control.",
        fmi1: {
            export: "unsupported",
            import: "unsupported",
            slave: "available",
            master: "planned",
        },
        fmi2: {
            export: "unsupported",
            import: "unsupported",
            slave: "available",
            master: "planned",
        },
        vendorId: "Controllab",
    },
    {
        id: "20sim4C",
        displayName: "20-sim 4C",
        homepage: "http://www.20sim4C.com/",
        email: "undefined",
        note: "Rapid prototyping tool for embedded hardware and industrial controllers.",
        fmi1: {
            export: "unsupported",
            import: "planned",
            slave: "unsupported",
            master: "planned",
        },
        fmi2: {
            export: "unsupported",
            import: "planned",
            slave: "unsupported",
            master: "planned",
        },
        vendorId: "Controllab",
    },
    {
        id: "AMESim",
        displayName: "Amesim",
        homepage: "http://www.plm.automation.siemens.com/en_us/products/lms/imagine-lab/index.shtml",
        email: "undefined",
        note:
            "Integrated simulation platform for the analysis of multi-domain mechatronics systems by Siemens PLM Software",
        fmi1: {
            export: "available",
            import: "available",
            slave: "available",
            master: "available",
        },
        fmi2: {
            export: "available",
            import: "available",
            slave: "available",
            master: "available",
        },
        vendorId: "Siemens",
    },
    {
        id: "ANSYSDesignXplorer",
        displayName: "ANSYS DesignXplorer",
        homepage: "http://www.ansys.com/Products/Platform/ANSYS-DesignXplorer",
        email: "Simon.Pereira@ANSYS.com",
        note: "DesignXplorer is able to export a computed response surface as an FMU.",
        fmi1: {
            export: "available",
            import: "unsupported",
            slave: "unsupported",
            master: "unsupported",
        },
        fmi2: {
            export: "unsupported",
            import: "unsupported",
            slave: "unsupported",
            master: "unsupported",
        },
        vendorId: "ANSYS",
    },
    {
        id: "ANSYS_SCADE_Display",
        displayName: "ANSYS SCADE Display",
        homepage: "http://www.ansys.com/Products/Simulation+Technology/Systems+&+Embedded+Software/ANSYS+SCADE+Display",
        email: "undefined",
        note:
            'SCADE Display facilitates embedded graphics, display and HMI development and certified code generation for safety-critical displays from <a href="http://www.ansys.com">ANSYS</a>.',
        fmi1: {
            export: "available",
            import: "unsupported",
            slave: "available",
            master: "unsupported",
        },
        fmi2: {
            export: "unsupported",
            import: "unsupported",
            slave: "unsupported",
            master: "unsupported",
        },
        vendorId: "ANSYS",
    },
    {
        id: "ANSYS_SCADE_Suite",
        displayName: "ANSYS SCADE Suite",
        homepage: "http://www.ansys.com/Products/Simulation+Technology/Systems+&+Embedded+Software/ANSYS+SCADE+Suite",
        email: "undefined",
        note:
            'SCADE Suite is a model-based development environment with certified code generation for safety critical embedded applications from <a href="http://www.ansys.com">ANSYS</a>.',
        fmi1: {
            export: "available",
            import: "unsupported",
            slave: "available",
            master: "unsupported",
        },
        fmi2: {
            export: "unsupported",
            import: "unsupported",
            slave: "unsupported",
            master: "unsupported",
        },
        vendorId: "ANSYS",
    },
    {
        id: "ANSYS_Simplorer",
        displayName: "ANSYS Simplorer",
        homepage: "http://www.ansys.com/Products/Systems/ANSYS-Simplorer",
        email: "undefined",
        note:
            'ANSYS Simplorer is a multi-domain, multi-technology simulation program from <a href="http://www.ansys.com">ANSYS</a>.',
        fmi1: {
            export: "available",
            import: "available",
            slave: "planned",
            master: "available",
        },
        fmi2: {
            export: "available",
            import: "available",
            slave: "planned",
            master: "available",
        },
        vendorId: "ANSYS",
    },
    {
        id: "ASim",
        displayName: "ASim - AUTOSAR Simulation",
        homepage: "http://www.3ds.com/products-services/catia/products/autosarbuilder/",
        email: "undefined",
        note: "AUTOSAR product from Dassault Syst&egrave",
        fmi1: {
            export: "available",
            import: "unsupported",
            slave: "available",
            master: "unsupported",
        },
        fmi2: {
            export: "available",
            import: "unsupported",
            slave: "available",
            master: "unsupported",
        },
        vendorId: "3DS",
    },
    {
        id: "AVL_CRUISE_M",
        displayName: "AVL CRUISE M",
        homepage: "https://www.avl.com/cruise-m",
        email: "undefined",
        note:
            "AVL CRUISE™ M is a realtime, multi-disciplinary, vehicle system simulation software used in office environments for the design of powertrains and thermal management systems, in HiL environments for control function development and calibration, and in testbed environments to provide simulation models for component testing.",
        fmi1: {
            export: "unsupported",
            import: "available",
            slave: "unsupported",
            master: "available",
        },
        fmi2: {
            export: "unsupported",
            import: "available",
            slave: "unsupported",
            master: "available",
        },
        vendorId: "AVL",
    },
    {
        id: "AVL_Cruise",
        displayName: "AVL CRUISE",
        homepage: "https://www.avl.com/cruise",
        email: "undefined",
        note:
            "Vehicle system analysis tool for the optimization of fuel efficiency, emission, performance and driveability, from office to HiL to testbed.",
        fmi1: {
            export: "planned",
            import: "available",
            slave: "available",
            master: "available",
        },
        fmi2: {
            export: "unsupported",
            import: "unsupported",
            slave: "unsupported",
            master: "unsupported",
        },
        vendorId: "AVL",
    },
    {
        id: "AVL_Model.CONNECT",
        displayName: "AVL Model.CONNECT",
        homepage: "https://www.avl.com/en/web/10138/iodp",
        email: "undefined",
        note: "Model.CONNECT&trade",
        fmi1: {
            export: "unsupported",
            import: "available",
            slave: "unsupported",
            master: "available",
        },
        fmi2: {
            export: "unsupported",
            import: "available",
            slave: "unsupported",
            master: "available",
        },
        vendorId: "AVL",
    },
    {
        id: "Adams",
        displayName: "Adams",
        homepage: "http://www.mscsoftware.com/Products/CAE-Tools/Adams.aspx",
        email: "undefined",
        note:
            'High end multibody dynamics simulation software from <a href="http://www.mscsoftware.com/">MSC Software</a>',
        fmi1: {
            export: "unsupported",
            import: "available",
            slave: "available",
            master: "available",
        },
        fmi2: {
            export: "unsupported",
            import: "available",
            slave: "available",
            master: "available",
        },
        vendorId: "MSC",
    },
    {
        id: "AtSource",
        displayName: "@Source",
        homepage: "http://podiumtechnology.co.uk/atsource-targets.htm",
        email: "undefined",
        note: "Simulink via @Source",
        fmi1: {
            export: "available",
            import: "unsupported",
            slave: "unsupported",
            master: "unsupported",
        },
        fmi2: {
            export: "unsupported",
            import: "unsupported",
            slave: "unsupported",
            master: "unsupported",
        },
        vendorId: "PodiumTechnology",
    },
    {
        id: "AutomationStudio",
        displayName: "B&R Automation Studio",
        homepage: "http://www.br-automation.com/en/",
        email: "undefined",
        note:
            'B&Rs Automation Studio is a software engineering platform for industrial automation targetting PLCs, industrial PCs, HMI and embedded controllers from <a href="http://www.br-automation.com/">B&R</a>.',
        fmi1: {
            export: "unsupported",
            import: "unsupported",
            slave: "unsupported",
            master: "unsupported",
        },
        fmi2: {
            export: "unsupported",
            import: "unsupported",
            slave: "unsupported",
            master: "unsupported",
        },
        vendorId: "br-automation",
    },
    {
        id: "Axisuite",
        displayName: "axisuite",
        homepage: "http://www.exothermia.com/home/index.php?option=com_content&view=article&id=120&Itemid=127&lang=en",
        email: "undefined",
        note:
            'Simulation of exhaust aftertreatment systems from <a href="http://www.exothermia.com/home/index.php">Exothermia</a>.',
        fmi1: {
            export: "unsupported",
            import: "unsupported",
            slave: "available",
            master: "unsupported",
        },
        fmi2: {
            export: "unsupported",
            import: "unsupported",
            slave: "available",
            master: "unsupported",
        },
        vendorId: "Exothermia",
    },
    {
        id: "BCVTB",
        displayName: "Building Controls Virtual Test Bed",
        homepage: "http://simulationresearch.lbl.gov/bcvtb/",
        email: "undefined",
        note:
            'BCVTB is a Software environment, based on <a href="http://ptolemy.eecs.berkeley.edu/index.htm">Ptolemy II</a>, for co-simulation of, and data exchange with, building energy and control systems.',
        fmi1: {
            export: "unsupported",
            import: "unsupported",
            slave: "unsupported",
            master: "available",
        },
        fmi2: {
            export: "unsupported",
            import: "unsupported",
            slave: "unsupported",
            master: "unsupported",
        },
        vendorId: "LBL",
    },
    {
        id: "BEAST",
        displayName: "BEAST",
        homepage: "http://www.skf.com",
        email: "dag.fritzson@skf.com",
        note:
            "BEAST is an advanced dynamic simulation tool for rolling bearings and other mechanical systems with contacts available through SKF Engineering Consultancy Services. BEAST analyzes what will happen under real conditions and predicts the behaviour of complex equipment that incorporates rolling bearings.",
        fmi1: {
            export: "unsupported",
            import: "unsupported",
            slave: "unsupported",
            master: "unsupported",
        },
        fmi2: {
            export: "unsupported",
            import: "unsupported",
            slave: "unsupported",
            master: "unsupported",
        },
        vendorId: "SKF",
    },
    {
        id: "CANoe",
        displayName: "CANoe",
        homepage: "http://vector.com/vi_canoe_de.html",
        email: "undefined",
        note:
            "CANoe is the comprehensive software tool for development, test and analysis of entire ECU networks and individual ECUs.",
        fmi1: {
            export: "available",
            import: "unsupported",
            slave: "planned",
            master: "available",
        },
        fmi2: {
            export: "available",
            import: "unsupported",
            slave: "planned",
            master: "available",
        },
        vendorId: "Vector",
    },
    {
        id: "CATIA",
        displayName: "CATIA",
        homepage:
            "http://org-www.3ds.com/products-services/catia/products/v6/portfolio/d/digital-product-experience/s/catia-systems-engineering/",
        email: "undefined",
        note:
            "Environment for Product Design and Innovation, including systems engineering tools based on Modelica, by Dassault Syst&egrave",
        fmi1: {
            export: "available",
            import: "available",
            slave: "available",
            master: "available",
        },
        fmi2: {
            export: "available",
            import: "available",
            slave: "available",
            master: "available",
        },
        vendorId: "3DS",
    },
    {
        id: "COE",
        displayName: "INTO-CPS Co-simulation Orchestration Engine (COE)",
        homepage: "http://into-cps.github.io/",
        email: "undefined",
        note:
            'A free standalone FMI co-simulation master implemented in Java with a JSON API. It is developed as part of the <a href="http://into-cps.au.dk/">INTO-CPS project</a>.',
        fmi1: {
            export: "unsupported",
            import: "unsupported",
            slave: "unsupported",
            master: "unsupported",
        },
        fmi2: {
            export: "unsupported",
            import: "unsupported",
            slave: "unsupported",
            master: "unsupported",
        },
        vendorId: "IntoCPS",
    },
    {
        id: "CPPFMU",
        displayName: "CPPFMU",
        homepage: "https://github.com/viproma/cppfmu",
        email: "undefined",
        note: "Interfaces and helper functions for writing FMI-compliant model/slave code in C++.",
        fmi1: {
            export: "planned",
            import: "unsupported",
            slave: "available",
            master: "unsupported",
        },
        fmi2: {
            export: "planned",
            import: "unsupported",
            slave: "available",
            master: "unsupported",
        },
        vendorId: "SINTEF",
    },
    {
        id: "Cameo",
        displayName: "Cameo Simulation Toolkit (MagicDraw plugin)",
        homepage: "",
        email: "undefined",
        note: "FMUs can be imported, represented, connected and co-simulated in SysML models.",
        fmi1: {
            export: "unsupported",
            import: "available",
            slave: "unsupported",
            master: "available",
        },
        fmi2: {
            export: "unsupported",
            import: "unsupported",
            slave: "unsupported",
            master: "unsupported",
        },
        vendorId: "NoMagic",
    },
    {
        id: "CarMaker",
        displayName: "CarMaker",
        homepage: "http://www.ipg.de/index.php?id=carmaker",
        email: "undefined",
        note: "CarMaker is an open test- and integration-platform for MiL, SiL and HiL.",
        fmi1: {
            export: "unsupported",
            import: "unsupported",
            slave: "unsupported",
            master: "available",
        },
        fmi2: {
            export: "unsupported",
            import: "unsupported",
            slave: "unsupported",
            master: "available",
        },
        vendorId: "IPG",
    },
    {
        id: "ControlBuild",
        displayName: "ControlBuild",
        homepage: "http://www.3ds.com/products-services/catia/products/controlbuild/",
        email: "undefined",
        note: "Environment for IEC 61131-3 control applications from Dassault Systèmes",
        fmi1: {
            export: "available",
            import: "available",
            slave: "available",
            master: "available",
        },
        fmi2: {
            export: "available",
            import: "available",
            slave: "available",
            master: "available",
        },
        vendorId: "3DS",
    },
    {
        id: "Coral",
        displayName: "Coral",
        homepage: "https://github.com/viproma/coral",
        email: "undefined",
        note: "Free and open-source software for distributed co-simulation.",
        fmi1: {
            export: "unsupported",
            import: "unsupported",
            slave: "unsupported",
            master: "available",
        },
        fmi2: {
            export: "unsupported",
            import: "unsupported",
            slave: "unsupported",
            master: "unsupported",
        },
        vendorId: "SINTEF",
    },
    {
        id: "CosiMate",
        displayName: "CosiMate",
        homepage: "http://www.cosimate.com/",
        email: "undefined",
        note: "Co-simulation Environment from ChiasTek",
        fmi1: {
            export: "unsupported",
            import: "available",
            slave: "unsupported",
            master: "available",
        },
        fmi2: {
            export: "unsupported",
            import: "unsupported",
            slave: "unsupported",
            master: "available",
        },
        vendorId: "Cosimate",
    },
    {
        id: "Cybernetica_CENIT",
        displayName: "Cybernetica CENIT",
        homepage: "http://cenit.cybernetica.no",
        email: "undefined",
        note: "Industrial product for nonlinear Model Predictive Control (NMPC) from Cybernetica.",
        fmi1: {
            export: "unsupported",
            import: "available",
            slave: "unsupported",
            master: "planned",
        },
        fmi2: {
            export: "unsupported",
            import: "unsupported",
            slave: "unsupported",
            master: "unsupported",
        },
        vendorId: "Cybernetica",
    },
    {
        id: "Cybernetica_ModelFit",
        displayName: "Cybernetica ModelFit",
        homepage: "http://modelfit.cybernetica.no",
        email: "undefined",
        note:
            "Software for model verification, state and parameter estimation, using logged process data. By Cybernetica.",
        fmi1: {
            export: "unsupported",
            import: "available",
            slave: "unsupported",
            master: "available",
        },
        fmi2: {
            export: "unsupported",
            import: "unsupported",
            slave: "unsupported",
            master: "unsupported",
        },
        vendorId: "Cybernetica",
    },
    {
        id: "DACCOSIM",
        displayName: "DACCOSIM",
        homepage: "http://daccosim.foundry.supelec.fr/",
        email: "undefined",
        note:
            "Master Algorithm generator & deployer from RISEGrid for a multi-OS, multi-threaded and distributed cosimulation implementing all the FMI 2.0 features.",
        fmi1: {
            export: "unsupported",
            import: "unsupported",
            slave: "unsupported",
            master: "unsupported",
        },
        fmi2: {
            export: "unsupported",
            import: "unsupported",
            slave: "unsupported",
            master: "unsupported",
        },
        vendorId: "EDF",
    },
    {
        id: "DAFUL",
        displayName: "DAFUL",
        homepage: "http://www.virtualmotion.co.kr/en/index.do",
        email: "undefined",
        note:
            'Intergrated structure and motion analysis software from <a href="http://www.virtualmotion.co.kr/en/index.do">VirtualMotion</a>.',
        fmi1: {
            export: "unsupported",
            import: "unsupported",
            slave: "available",
            master: "unsupported",
        },
        fmi2: {
            export: "unsupported",
            import: "unsupported",
            slave: "available",
            master: "unsupported",
        },
        vendorId: "VirtualMotion",
    },
    {
        id: "DSHplus",
        displayName: "DSHplus",
        homepage: "http://www.fluidon.com",
        email: "undefined",
        note: 'Fluid power simulation software from <a href="http://www.fluidon.com">FLUIDON</a>',
        fmi1: {
            export: "planned",
            import: "unsupported",
            slave: "available",
            master: "unsupported",
        },
        fmi2: {
            export: "unsupported",
            import: "unsupported",
            slave: "unsupported",
            master: "unsupported",
        },
        vendorId: "fluidon",
    },
    {
        id: "DS_FMU_Export_from_Simulink",
        displayName: "DS - FMU Export from Simulink",
        homepage: "http://www.dymola.com/FMI",
        email: "undefined",
        note: '<a href="http://www.dymola.com/FMI">FMI Kit for Simulink </a> provided by Dassault Syst&egrave',
        fmi1: {
            export: "available",
            import: "unsupported",
            slave: "available",
            master: "unsupported",
        },
        fmi2: {
            export: "available",
            import: "unsupported",
            slave: "available",
            master: "unsupported",
        },
        vendorId: "3DS",
    },
    {
        id: "DS_FMU_Import_into_Simulink",
        displayName: "DS - FMU Import into Simulink",
        homepage: "http://www.dymola.com/FMI",
        email: "undefined",
        note: '<a href="http://www.dymola.com/FMI">FMI Kit for Simulink </a> provided by Dassault Syst&egrave',
        fmi1: {
            export: "unsupported",
            import: "available",
            slave: "unsupported",
            master: "available",
        },
        fmi2: {
            export: "unsupported",
            import: "available",
            slave: "unsupported",
            master: "available",
        },
        vendorId: "3DS",
    },
    {
        id: "DYNA4",
        displayName: "DYNA4",
        homepage:
            "http://www.tesis-dynaware.com/en/products/dyna4-howtos-overview/dyna4-howto/use-of-modelica-based-models-in-dyna4.html",
        email: "undefined",
        note: 'Open and flexible simulation framework by <a href="http://www.tesis-dynaware.com">TESIS DYNAware</a>.',
        fmi1: {
            export: "unsupported",
            import: "available",
            slave: "unsupported",
            master: "available",
        },
        fmi2: {
            export: "unsupported",
            import: "available",
            slave: "unsupported",
            master: "available",
        },
        vendorId: "Tesis-Dynaware",
    },
    {
        id: "Dymola",
        displayName: "Dymola",
        homepage: "http://www.3ds.com/products-services/catia/capabilities/modelica-systems-simulation-info/dymola",
        email: "undefined",
        note: "Modelica environment from Dassault Syst&egrave",
        fmi1: {
            export: "available",
            import: "available",
            slave: "available",
            master: "available",
        },
        fmi2: {
            export: "available",
            import: "available",
            slave: "available",
            master: "available",
        },
        vendorId: "3DS",
    },
    {
        id: "ETAS_ASCMO",
        displayName: "ETAS - ASCMO",
        homepage: "http://www.etas.com/en/products/ascmo.php",
        email: "undefined",
        note:
            'Creation and export of statistical (meta) models using Design of Experiments (DoE) from <a href="http://www.etas.com/en/">ETAS</a>.',
        fmi1: {
            export: "unsupported",
            import: "unsupported",
            slave: "available",
            master: "unsupported",
        },
        fmi2: {
            export: "unsupported",
            import: "unsupported",
            slave: "available",
            master: "unsupported",
        },
        vendorId: "ETAS",
    },
    {
        id: "ETAS_FMI",
        displayName: "ETAS - FMI-based Integration and Simulation Platform",
        homepage: "https://www.modelica.org/publications/newsletters/2014-1/index_html",
        email: "undefined",
        note: 'Integration and simulation platform based on FMI 1.0 from <a href="http://www.etas.com/en">ETAS</a>.',
        fmi1: {
            export: "unsupported",
            import: "planned",
            slave: "unsupported",
            master: "planned",
        },
        fmi2: {
            export: "unsupported",
            import: "unsupported",
            slave: "unsupported",
            master: "unsupported",
        },
        vendorId: "ETAS",
    },
    {
        id: "ETAS_FMU_Generator_for_ASCET",
        displayName: "ETAS - FMU Generator for ASCET",
        homepage: "https://www.modelica.org/publications/newsletters/2014-1/index_html",
        email: "undefined",
        note:
            'FMU Generator for <a href="http://www.etas.com/en/products/ascet_software_products.php">ASCET</a> from <a href="http://www.etas.com/en">ETAS</a>.',
        fmi1: {
            export: "planned",
            import: "unsupported",
            slave: "unsupported",
            master: "unsupported",
        },
        fmi2: {
            export: "unsupported",
            import: "unsupported",
            slave: "unsupported",
            master: "unsupported",
        },
        vendorId: "ETAS",
    },
    {
        id: "ETAS_FMU_Generator_for_Simulink",
        displayName: "ETAS - FMU Generator for Simulink<sup>&reg",
        homepage: "https://www.modelica.org/publications/newsletters/2014-1/index_html",
        email: "undefined",
        note: "FMU Generator for Simulink<sup>&reg",
        fmi1: {
            export: "planned",
            import: "unsupported",
            slave: "planned",
            master: "unsupported",
        },
        fmi2: {
            export: "unsupported",
            import: "unsupported",
            slave: "unsupported",
            master: "unsupported",
        },
        vendorId: "ETAS",
    },
    {
        id: "ETAS_INCA_FLOW",
        displayName: "ETAS - INCA-FLOW (MiL/SiL Connector)",
        homepage: "http://www.etas.com/en/products/inca_flow.php",
        email: "undefined",
        note: "Guided and automated calibration of FMUs with connection to ETAS INCA.",
        fmi1: {
            export: "unsupported",
            import: "planned",
            slave: "unsupported",
            master: "available",
        },
        fmi2: {
            export: "unsupported",
            import: "unsupported",
            slave: "unsupported",
            master: "unsupported",
        },
        vendorId: "ETAS",
    },
    {
        id: "ETAS_ISOLAR_EVE",
        displayName: "ETAS - ISOLAR-EVE (ETAS Virtual ECU)",
        homepage: "http://www.etas.com/en/products/isolar_eve.php",
        email: "undefined",
        note:
            'PC based platform from <a href="http://www.etas.com/en">ETAS</a> for ECU software validation at the component, sub-system or system level',
        fmi1: {
            export: "unsupported",
            import: "unsupported",
            slave: "available",
            master: "unsupported",
        },
        fmi2: {
            export: "unsupported",
            import: "unsupported",
            slave: "available",
            master: "unsupported",
        },
        vendorId: "ETAS",
    },
    {
        id: "ETAS_LABCAR_OPERATOR",
        displayName: "ETAS - LABCAR-OPERATOR",
        homepage: "http://www.etas.com/en/products/labcar_operator.php",
        email: "undefined",
        note:
            "Frontend for ETAS HiL systems LABCAR, operating on the creation of experiments and their subsequent execution.",
        fmi1: {
            export: "unsupported",
            import: "unsupported",
            slave: "unsupported",
            master: "available",
        },
        fmi2: {
            export: "unsupported",
            import: "unsupported",
            slave: "unsupported",
            master: "unsupported",
        },
        vendorId: "ETAS",
    },
    {
        id: "Easy5",
        displayName: "Easy5",
        homepage: "http://http://www.mscsoftware.com/product/easy5",
        email: "undefined",
        note:
            'High performance simulation environment for multi-domain system dynamics from <a href="http://www.mscsoftware.com/">MSC Software</a>.',
        fmi1: {
            export: "unsupported",
            import: "available",
            slave: "available",
            master: "available",
        },
        fmi2: {
            export: "unsupported",
            import: "available",
            slave: "available",
            master: "available",
        },
        vendorId: "MSC",
    },
    {
        id: "EcosimPro",
        displayName: "EcosimPro",
        homepage: "http://www.ecosimpro.com/products/ecosimpro/",
        email: "undefined",
        note: "EcosimPro, System Modelling and Simulation Software",
        fmi1: {
            export: "unsupported",
            import: "unsupported",
            slave: "unsupported",
            master: "unsupported",
        },
        fmi2: {
            export: "unsupported",
            import: "unsupported",
            slave: "unsupported",
            master: "unsupported",
        },
        vendorId: "EcosimPro",
    },
    {
        id: "EnergyPlus",
        displayName: "EnergyPlus",
        homepage: "http://simulationresearch.lbl.gov/fmu/EnergyPlus/export/index.html",
        email: "undefined",
        note: "Whole building energy simulation program",
        fmi1: {
            export: "unsupported",
            import: "unsupported",
            slave: "available",
            master: "available",
        },
        fmi2: {
            export: "unsupported",
            import: "unsupported",
            slave: "unsupported",
            master: "unsupported",
        },
        vendorId: "LBL",
    },
    {
        id: "FMIBench",
        displayName: "FMI Bench",
        homepage: "https://pmsf.eu/products/fmibench/",
        email: "fmibench@pmsf.eu",
        note:
            'Workbench for inspection, customization and pre-integration of FMUs including parallelization and stand-alone simulation generation from <href="https://pmsf.eu/">PMSF</a>.',
        fmi1: {
            export: "available",
            import: "available",
            slave: "available",
            master: "available",
        },
        fmi2: {
            export: "available",
            import: "available",
            slave: "available",
            master: "available",
        },
        vendorId: "PMSF",
    },
    {
        id: "FMILibrary",
        displayName: "FMI Library",
        homepage: "http://www.fmi-library.org/",
        email: "undefined",
        note:
            'Open source (BSD) C library for integration of FMI technology in custom applications by <a href="http://www.modelon.com/"​>Modelon</a>.',
        fmi1: {
            export: "planned",
            import: "available",
            slave: "planned",
            master: "available",
        },
        fmi2: {
            export: "planned",
            import: "available",
            slave: "planned",
            master: "available",
        },
        vendorId: "Modelon",
    },
    {
        id: "FMITarget_for_Simulink_Coder",
        displayName: "FMI Target for Simulink Coder",
        homepage: "https://cdn.simulationx.de/en/pdf/FMI-Target-for-Simulink-Coder.pdf",
        email: "undefined",
        note:
            'Export of stand-alone FMUs for Co-Simulation from Simulink using Simulink Coder - provided by <a href="http://www.itisim.com/">ITI</a>',
        fmi1: {
            export: "unsupported",
            import: "unsupported",
            slave: "available",
            master: "unsupported",
        },
        fmi2: {
            export: "unsupported",
            import: "unsupported",
            slave: "unsupported",
            master: "unsupported",
        },
        vendorId: "ESi",
    },
    {
        id: "FMIToolbox_MATLAB",
        displayName: "FMI Toolbox for MATLAB/Simulink",
        homepage: "http://www.modelon.com/products/fmi-toolbox-for-matlab",
        email: "undefined",
        note:
            '<a href="http://www.modelon.com/products/fmi-toolbox-for-matlab">The FMI Toolbox for MATLAB/Simulink</a> from <a href="http://www.modelon.com">Modelon</a> enables FMU import and export for MATLAB/Simulink for both model exchange and co-simulation.',
        fmi1: {
            export: "available",
            import: "available",
            slave: "available",
            master: "available",
        },
        fmi2: {
            export: "available",
            import: "available",
            slave: "available",
            master: "available",
        },
        vendorId: "Modelon",
    },
    {
        id: "FMI_Addin_for_Excel",
        displayName: "FMI Add-in for Excel",
        homepage: "http://www.modelon.com/products/fmi-add-in-for-excel/",
        email: "undefined",
        note:
            '<a href="http://www.modelon.com/products/fmi-add-in-for-excel/">FMI Add-in for Microsoft Excel</a> by ​<a href="http://www.modelon.com/"​>Modelon</a>. Offers support for batch simulation of FMUs.',
        fmi1: {
            export: "unsupported",
            import: "unsupported",
            slave: "unsupported",
            master: "available",
        },
        fmi2: {
            export: "unsupported",
            import: "unsupported",
            slave: "unsupported",
            master: "unsupported",
        },
        vendorId: "Modelon",
    },
    {
        id: "FMI_Blockset_for_Simulink",
        displayName: "FMI Blockset for Simulink",
        homepage: "http://www.claytex.com/products/fmi-blockset/",
        email: "undefined",
        note:
            'The FMI Blockset for Simulink enables the import of FMU\'s for use in Simulink - developed by <a href="http://www.claytex.com">Claytex</a>.',
        fmi1: {
            export: "unsupported",
            import: "unsupported",
            slave: "unsupported",
            master: "available",
        },
        fmi2: {
            export: "unsupported",
            import: "unsupported",
            slave: "unsupported",
            master: "available",
        },
        vendorId: "Claytex",
    },
    {
        id: "FMI_Composer",
        displayName: "FMI Composer",
        homepage: "http://www.modelon.com/products/fmi-tools/fmi-composer/",
        email: "undefined",
        note:
            '<a href="http://www.modelon.com/products/fmi-tools/fmi-composer/">FMI Composer</a> from <a href="http://www.modelon.com">Modelon</a> is a software platform enabling users to build system models from multiple FMUs. FMI Composer is built entirely on the FMI and upcoming SSP standards.',
        fmi1: {
            export: "unsupported",
            import: "planned",
            slave: "unsupported",
            master: "planned",
        },
        fmi2: {
            export: "unsupported",
            import: "planned",
            slave: "unsupported",
            master: "planned",
        },
        vendorId: "Modelon",
    },
    {
        id: "FMI_addon_for_NI_VeriStand",
        displayName: "FMI add-on for NI VeriStand",
        homepage: "http://www.dofware.com/img/FMI_Flyer.pdf",
        email: "undefined",
        note:
            '<a href="http://www.ni.com/veristand/">NI VeriStand</a> supports FMI through the use of the <a href="http://www.dofware.com/img/FMI_Flyer.pdf">FMI add-on for NI VeriStand</a> from <a href="http://www.dofware.com/">Dofware</a>',
        fmi1: {
            export: "unsupported",
            import: "available",
            slave: "unsupported",
            master: "available",
        },
        fmi2: {
            export: "unsupported",
            import: "unsupported",
            slave: "unsupported",
            master: "unsupported",
        },
        vendorId: "Dofware",
    },
    {
        id: "FMPy",
        displayName: "FMPy",
        homepage: "https://github.com/CATIA-Systems/FMPy",
        email: "undefined",
        note: "A Python library to simulate FMUs",
        fmi1: {
            export: "unsupported",
            import: "available",
            slave: "unsupported",
            master: "available",
        },
        fmi2: {
            export: "unsupported",
            import: "available",
            slave: "unsupported",
            master: "available",
        },
        vendorId: "3DS",
    },
    {
        id: "FMUSDK",
        displayName: "FMUSDK",
        homepage: "http://www.qtronic.de/en/fmusdk.html",
        email: "undefined",
        note: 'FMU Software Development Kit from <a href="http://www.qtronic.de/">QTronic</a>.',
        fmi1: {
            export: "available",
            import: "available",
            slave: "available",
            master: "available",
        },
        fmi2: {
            export: "unsupported",
            import: "unsupported",
            slave: "unsupported",
            master: "unsupported",
        },
        vendorId: "QTronic",
    },
    {
        id: "Flowmaster",
        displayName: "Flowmaster",
        homepage: "http://www.mentor.com/products/mechanical/flowmaster/flowmaster-automotive/options",
        email: "undefined",
        note:
            'High capability 1D CFD tool for thermo-fluid simulation from <a href="http://www.mentor.com/products/mechanical/flowmaster/">Mentor Graphics</a>.',
        fmi1: {
            export: "available",
            import: "unsupported",
            slave: "unsupported",
            master: "unsupported",
        },
        fmi2: {
            export: "unsupported",
            import: "unsupported",
            slave: "unsupported",
            master: "unsupported",
        },
        vendorId: "Mentor",
    },
    {
        id: "GES",
        displayName: "General Energy Systems (GES)",
        homepage: "http://www.tno.nl/ges",
        email: "undefined",
        note:
            'GES is an object oriented simulation tool, for dynamic and static (algebraic) systems, Based on a hybrid bondgraph model. The tool is mainly used for ship power designs. Provided by <a href="http://www.tno.nl/ges">TNO</a>.',
        fmi1: {
            export: "available",
            import: "available",
            slave: "planned",
            master: "planned",
        },
        fmi2: {
            export: "available",
            import: "available",
            slave: "planned",
            master: "planned",
        },
        vendorId: "TNO",
    },
    {
        id: "GT_SUITE",
        displayName: "GT-SUITE",
        homepage: "http://www.gtisoft.com/",
        email: "undefined",
        note: "Multi-Physics Simulation Platform for Powertrain and Vehicle Systems",
        fmi1: {
            export: "unsupported",
            import: "available",
            slave: "available",
            master: "available",
        },
        fmi2: {
            export: "unsupported",
            import: "available",
            slave: "available",
            master: "available",
        },
        vendorId: "GammaTechnologies",
    },
    {
        id: "Hopsan",
        displayName: "Hopsan",
        homepage: "http://www.iei.liu.se/flumes/system-simulation/hopsan?l=en",
        email: "undefined",
        note:
            "Hopsan is a free simulation tool developed at Linköping University. It is using distributed solver techniques with good support for parallelism using multi-core processors.",
        fmi1: {
            export: "available",
            import: "available",
            slave: "unsupported",
            master: "unsupported",
        },
        fmi2: {
            export: "unsupported",
            import: "unsupported",
            slave: "unsupported",
            master: "unsupported",
        },
        vendorId: "LIU",
    },
    {
        id: "IBM_Rational_Rhapsody",
        displayName: "IBM Rational Rhapsody",
        homepage: "http://www.ibm.com/software/products/en/ratirhapfami",
        email: "undefined",
        note: "IBM&reg",
        fmi1: {
            export: "available",
            import: "planned",
            slave: "planned",
            master: "planned",
        },
        fmi2: {
            export: "unsupported",
            import: "unsupported",
            slave: "unsupported",
            master: "unsupported",
        },
        vendorId: "IBM",
    },
    {
        id: "ICOS",
        displayName: 'ICOS "Independent Co-Simulation"',
        homepage: "http://vif.tugraz.at/en/products/icos/",
        email: "undefined",
        note: 'ICOS is a co-simulation tool developed by <a href="http://vif.tugraz.at/en/">Virtual Vehicle</a>',
        fmi1: {
            export: "unsupported",
            import: "available",
            slave: "available",
            master: "available",
        },
        fmi2: {
            export: "unsupported",
            import: "unsupported",
            slave: "unsupported",
            master: "unsupported",
        },
        vendorId: "tugraz",
    },
    {
        id: "IGNITE",
        displayName: "IGNITE",
        homepage: "http://www.ricardo.com/en-GB/What-we-do/Software/Products/IGNITE/",
        email: "undefined",
        note:
            'Physics-based system simulation software for complete vehicle system modeling and simulation from <a href="http://www.ricardo.com/software">Ricardo Software</a>.',
        fmi1: {
            export: "unsupported",
            import: "unsupported",
            slave: "planned",
            master: "available",
        },
        fmi2: {
            export: "unsupported",
            import: "unsupported",
            slave: "planned",
            master: "available",
        },
        vendorId: "Ricardo",
    },
    {
        id: "JFMI",
        displayName: "JFMI",
        homepage: "http://ptolemy.berkeley.edu/java/jfmi/",
        email: "undefined",
        note: "A Java Wrapper for the Functional Mock-up Interface, based on FMU SDK",
        fmi1: {
            export: "unsupported",
            import: "unsupported",
            slave: "available",
            master: "available",
        },
        fmi2: {
            export: "unsupported",
            import: "unsupported",
            slave: "unsupported",
            master: "unsupported",
        },
        vendorId: "UCB",
    },
    {
        id: "JModelica.org",
        displayName: "JModelica.org",
        homepage: "http://www.jmodelica.org",
        email: "undefined",
        note: 'Open source Modelica environment from <a href="http://www.modelon.com">Modelon</a>',
        fmi1: {
            export: "available",
            import: "available",
            slave: "available",
            master: "available",
        },
        fmi2: {
            export: "unsupported",
            import: "unsupported",
            slave: "unsupported",
            master: "unsupported",
        },
        vendorId: "Modelon",
    },
    {
        id: "JavaFMI",
        displayName: "JavaFMI",
        homepage: "https://bitbucket.org/siani/javafmi/wiki/Home",
        email: "undefined",
        note:
            "JavaFMI is a Java wrapper for the Functional Mock-up Interface (1.0 or 2.0) both for Windows/Linux 32 or 64 bit OS.",
        fmi1: {
            export: "unsupported",
            import: "unsupported",
            slave: "unsupported",
            master: "available",
        },
        fmi2: {
            export: "unsupported",
            import: "unsupported",
            slave: "unsupported",
            master: "available",
        },
        vendorId: "SIANI",
    },
    {
        id: "LMS_Virtual.Lab_Motion",
        displayName: "LMS Virtual.Lab Motion",
        homepage: "http://www.lmsintl.com/simulation/virtuallab/motion",
        email: "undefined",
        note: "Virtual.Lab Motion is a high end multi body software from LMS International",
        fmi1: {
            export: "unsupported",
            import: "available",
            slave: "available",
            master: "available",
        },
        fmi2: {
            export: "unsupported",
            import: "unsupported",
            slave: "unsupported",
            master: "unsupported",
        },
        vendorId: "Siemens",
    },
    {
        id: "MESSINA",
        displayName: "MESSINA",
        homepage: "https://www.assystem-germany.com/en/products/messina/",
        email: "undefined",
        note:
            '<a href="https://www.assystem-germany.com/en/products/messina/">MESSINA</a> is a test platform for model-based ECU function development.',
        fmi1: {
            export: "unsupported",
            import: "available",
            slave: "unsupported",
            master: "available",
        },
        fmi2: {
            export: "unsupported",
            import: "unsupported",
            slave: "unsupported",
            master: "unsupported",
        },
        vendorId: "assystem",
    },
    {
        id: "MWorks",
        displayName: "MWorks",
        homepage: "http://www.tongyuan.cc/",
        email: "undefined",
        note: 'Modelica environment from Suzhou <a href="http://www.tongyuan.cc/">Tongyuan</a>',
        fmi1: {
            export: "available",
            import: "available",
            slave: "available",
            master: "available",
        },
        fmi2: {
            export: "available",
            import: "available",
            slave: "available",
            master: "available",
        },
        vendorId: "tonqyuan",
    },
    {
        id: "MapleSim",
        displayName: "MapleSim",
        homepage: "http://www.maplesoft.com/products/maplesim/modelica.aspx",
        email: "undefined",
        note: "Modelica-based modeling and simulation tool from Maplesoft",
        fmi1: {
            export: "available",
            import: "unsupported",
            slave: "available",
            master: "unsupported",
        },
        fmi2: {
            export: "available",
            import: "unsupported",
            slave: "available",
            master: "unsupported",
        },
        vendorId: "Maplesoft",
    },
    {
        id: "MechanicalSimulation",
        displayName: "Mechanical Simulation: CarSim, TruckSim, BikeSim",
        homepage: "http://www.carsim.com/",
        email: "undefined",
        note:
            'CarSim, TruckSim, and BikeSim are vehicle dynamics software solutions from <a href="http://www.carsim.com/">Mechanical Simulation</a> that support XiL development workflows and power real-time driving simulators around the globe.',
        fmi1: {
            export: "unsupported",
            import: "unsupported",
            slave: "available",
            master: "planned",
        },
        fmi2: {
            export: "unsupported",
            import: "unsupported",
            slave: "available",
            master: "planned",
        },
        vendorId: "CarSim",
    },
    {
        id: "MoBA_Lab",
        displayName: "MoBA Lab",
        homepage: "http://www.moba-lab.de/fmiCrosscheck",
        email: "undefined",
        note:
            "MoBA Lab gives the user a wide-ranging portfolio of different tools for the model-based development process of thermal and other types of systems. The MoBA Simulator is available for Excel, Python, C++, and various other environments.",
        fmi1: {
            export: "planned",
            import: "available",
            slave: "planned",
            master: "available",
        },
        fmi2: {
            export: "planned",
            import: "available",
            slave: "planned",
            master: "available",
        },
        vendorId: "MoBA",
    },
    {
        id: "Morphee",
        displayName: "Morphee",
        homepage: "http://www.fev.com/what-we-do/testing-solutions/products/software/morphee.html",
        email: "hotline@fev.com",
        note:
            'MORPHEE is a system for automation, simulation and calibration from <a href="http://www.fev.com/">FEV</a>.',
        fmi1: {
            export: "unsupported",
            import: "planned",
            slave: "unsupported",
            master: "planned",
        },
        fmi2: {
            export: "unsupported",
            import: "planned",
            slave: "unsupported",
            master: "planned",
        },
        vendorId: "FEV",
    },
    {
        id: "NI_LabVIEW",
        displayName: "NI LabVIEW",
        homepage: "http://www.ni.com/labview/",
        email: "undefined",
        note: "Graphical programming environment for measurement, test, and control systems from National Instruments",
        fmi1: {
            export: "unsupported",
            import: "planned",
            slave: "unsupported",
            master: "unsupported",
        },
        fmi2: {
            export: "unsupported",
            import: "unsupported",
            slave: "unsupported",
            master: "unsupported",
        },
        vendorId: "NI",
    },
    {
        id: "OPTIMICA_Studio",
        displayName: "OPTIMICA Studio",
        homepage: "http://www.modelon.com/products/",
        email: "undefined",
        note: "Discontinued",
        fmi1: {
            export: "unsupported",
            import: "unsupported",
            slave: "unsupported",
            master: "unsupported",
        },
        fmi2: {
            export: "unsupported",
            import: "unsupported",
            slave: "unsupported",
            master: "unsupported",
        },
        vendorId: "Modelon",
    },
    {
        id: "OpenModelica",
        displayName: "OpenModelica",
        homepage: "https://openmodelica.org",
        email: "openmodelica@ida.liu.se",
        note: 'Open source Modelica environment from <a href="https://openmodelica.org/home/consortium">OSMC</a>',
        fmi1: {
            export: "available",
            import: "available",
            slave: "unsupported",
            master: "unsupported",
        },
        fmi2: {
            export: "available",
            import: "available",
            slave: "unsupported",
            master: "unsupported",
        },
        vendorId: "OM",
    },
    {
        id: "Overture",
        displayName: "Overture",
        homepage: "http://overturetool.org/",
        email: "undefined",
        note:
            "Modelling tool for the Vienna Development Method with supports for export of tool wrapper and source code FMU's.",
        fmi1: {
            export: "unsupported",
            import: "unsupported",
            slave: "unsupported",
            master: "unsupported",
        },
        fmi2: {
            export: "unsupported",
            import: "unsupported",
            slave: "unsupported",
            master: "unsupported",
        },
        vendorId: "overture",
    },
    {
        id: "PROOSIS",
        displayName: "PROOSIS",
        homepage: "http://www.ecosimpro.com/products/proosis/",
        email: "undefined",
        note: "PROOSIS, Propulsion Object-Oriented Simulation Software",
        fmi1: {
            export: "unsupported",
            import: "unsupported",
            slave: "unsupported",
            master: "unsupported",
        },
        fmi2: {
            export: "unsupported",
            import: "unsupported",
            slave: "unsupported",
            master: "unsupported",
        },
        vendorId: "EcosimPro",
    },
    {
        id: "Ptolemy_II",
        displayName: "Ptolemy II",
        homepage: "http://ptolemy.eecs.berkeley.edu/index.htm",
        email: "undefined",
        note: "Software environment for design and analysis of heterogeneous systems.",
        fmi1: {
            export: "unsupported",
            import: "unsupported",
            slave: "unsupported",
            master: "planned",
        },
        fmi2: {
            export: "unsupported",
            import: "unsupported",
            slave: "unsupported",
            master: "unsupported",
        },
        vendorId: "UCB",
    },
    {
        id: "PyFMI",
        displayName: "PyFMI",
        homepage: "http://pypi.python.org/pypi/PyFMI/",
        email: "undefined",
        note:
            'For Python via the open source package <a href="http://pypi.python.org/pypi/PyFMI/">PyFMI</a> from  <a href="http://www.modelon.com">Modelon</a>. Also available as part of the <a href="http://www.jmodelica.org/">JModelica.org</a> platform.',
        fmi1: {
            export: "unsupported",
            import: "available",
            slave: "unsupported",
            master: "available",
        },
        fmi2: {
            export: "unsupported",
            import: "available",
            slave: "unsupported",
            master: "available",
        },
        vendorId: "Modelon",
    },
    {
        id: "RecurDyn",
        displayName: "RecurDyn",
        homepage: "http://eng.functionbay.co.kr",
        email: "undefined",
        note:
            'High End Multi Flexible Body Dynamcis Software from <a href="http://www.functionbay.co.kr">FunctionBay</a>',
        fmi1: {
            export: "planned",
            import: "planned",
            slave: "available",
            master: "available",
        },
        fmi2: {
            export: "planned",
            import: "planned",
            slave: "available",
            master: "available",
        },
        vendorId: "FunctionBay",
    },
    {
        id: "Reference_FMUs",
        displayName: "Reference FMUs",
        homepage: "undefined",
        email: "undefined",
        note: "Reference FMUs supplied by enthusiasts and volunteers to show case specific FMU features",
        fmi1: {
            export: "planned",
            import: "unsupported",
            slave: "planned",
            master: "unsupported",
        },
        fmi2: {
            export: "unsupported",
            import: "unsupported",
            slave: "unsupported",
            master: "unsupported",
        },
        vendorId: "FMI",
    },
    {
        id: "SIMPACK",
        displayName: "SIMPACK",
        homepage: "http://www.simpack.com/mbs-software-products.html",
        email: "markus.friedrich@3ds.com",
        note:
            'High end multi-body simulation software from  <a href="http://www.simpack.com/mbs-software-products.html">Dassault Syst&egrave',
        fmi1: {
            export: "unsupported",
            import: "available",
            slave: "available",
            master: "available",
        },
        fmi2: {
            export: "unsupported",
            import: "available",
            slave: "available",
            master: "available",
        },
        vendorId: "3DS",
    },
    {
        id: "ScilabXcos",
        displayName: "Scilab/Xcos FMU wrapper",
        homepage: "http://www.scilab.org/scilab/interoperability/fmi-module",
        email: "undefined",
        note:
            'FMI support for <a href="http://www.scilab.org/">Scilab / Xcos</a> a free and open source software for numerical computation.',
        fmi1: {
            export: "available",
            import: "available",
            slave: "available",
            master: "available",
        },
        fmi2: {
            export: "available",
            import: "available",
            slave: "available",
            master: "available",
        },
        vendorId: "Scilab",
    },
    {
        id: "Silver",
        displayName: "Silver",
        homepage: "http://www.qtronic.com/en/silver.html",
        email: "fmu@qtronic.de",
        note:
            'Generation of virtual ECUs and virtual integration platform for Software in the Loop from <a href="http://www.qtronic.de/">QTronic</a>.',
        fmi1: {
            export: "available",
            import: "available",
            slave: "available",
            master: "available",
        },
        fmi2: {
            export: "unsupported",
            import: "available",
            slave: "available",
            master: "available",
        },
        vendorId: "QTronic",
    },
    {
        id: "SimWB",
        displayName: "Simulation Workbench (SimWB)",
        homepage: "http://wiki.simwb.com/",
        email: "undefined",
        note:
            'SimWB is an open, powerful framework to run SIL, HIL, and MIL simulations under <a href="https://www.ccur.com/">Concurrent\'s</a> hard real-time <a href="https://www.ccur.com/linux/products/redhawk/">RedHawk</a> OS that runs on COTS hardware.',
        fmi1: {
            export: "unsupported",
            import: "unsupported",
            slave: "unsupported",
            master: "available",
        },
        fmi2: {
            export: "unsupported",
            import: "unsupported",
            slave: "unsupported",
            master: "available",
        },
        vendorId: "SimWB",
    },
    {
        id: "SimulationX",
        displayName: "SimulationX",
        homepage: "https://www.simulationx.com/simulation-software/experts/fmi-simulation.html",
        email: "undefined",
        note:
            'Multi-domain simulation tool for design, analysis and virtual prototyping of complex systems developed by <a href="http://www.itisim.com/">ESI ITI GmbH</a>.',
        fmi1: {
            export: "available",
            import: "available",
            slave: "available",
            master: "available",
        },
        fmi2: {
            export: "available",
            import: "available",
            slave: "available",
            master: "available",
        },
        vendorId: "ESi",
    },
    {
        id: "Squish",
        displayName: "Squish GUI Tester",
        homepage: "https://squish.froglogic.com",
        email: "squish@froglogic.com",
        note:
            "Squish is a GUI Test Automation Tool. As an FMU importer, Squish test scripts can access all variables exposed by a FMU and is responsible for driving the simulation process.",
        fmi1: {
            export: "unsupported",
            import: "unsupported",
            slave: "unsupported",
            master: "unsupported",
        },
        fmi2: {
            export: "unsupported",
            import: "unsupported",
            slave: "unsupported",
            master: "unsupported",
        },
        vendorId: "froglogic",
    },
    {
        id: "SystemModeler",
        displayName: "SystemModeler",
        homepage: "http://www.wolfram.com/system-modeler",
        email: "undefined",
        note: 'Modelica environment from <a href="http://www.wolfram.com">Wolfram Research</a>.',
        fmi1: {
            export: "available",
            import: "available",
            slave: "planned",
            master: "planned",
        },
        fmi2: {
            export: "available",
            import: "available",
            slave: "planned",
            master: "planned",
        },
        vendorId: "Wolfram",
    },
    {
        id: "TLK_FMI_Suite",
        displayName: "TLK FMI Suite",
        homepage: "http://www.tlk-thermo.com/",
        email: "undefined",
        note: "TLK FMI Suite provides LabVIEW and Simulink blocks for FMU simulation",
        fmi1: {
            export: "unsupported",
            import: "available",
            slave: "unsupported",
            master: "available",
        },
        fmi2: {
            export: "unsupported",
            import: "unsupported",
            slave: "unsupported",
            master: "unsupported",
        },
        vendorId: "TLK",
    },
    {
        id: "TLK_TISC_Suite",
        displayName: "TLK TISC Suite",
        homepage: "http://www.tlk-thermo.de",
        email: "undefined",
        note: "Co-simulation environment from TLK-Thermo",
        fmi1: {
            export: "unsupported",
            import: "available",
            slave: "unsupported",
            master: "available",
        },
        fmi2: {
            export: "unsupported",
            import: "unsupported",
            slave: "unsupported",
            master: "unsupported",
        },
        vendorId: "TLK",
    },
    {
        id: "TWT_CoSim_Framework",
        displayName: "TWT Co-Simulation Framework",
        homepage: "https://www.twt-gmbh.de/en/produkte/co-simulation/cosimlab.html",
        email: "undefined",
        note: "Communication layer tool to flexibly plug together models for performing a co-simulation",
        fmi1: {
            export: "unsupported",
            import: "unsupported",
            slave: "available",
            master: "available",
        },
        fmi2: {
            export: "unsupported",
            import: "unsupported",
            slave: "unsupported",
            master: "unsupported",
        },
        vendorId: "TWT",
    },
    {
        id: "TWT_FMU_TrustCentre",
        displayName: "TWT FMU Trust Centre",
        homepage: "https://www.twt-gmbh.de/en/produkte/co-simulation/functional-mock-up-trust-centre.html",
        email: "undefined",
        note: "Cryptographic protection and signature of models including their safe PLM storage",
        fmi1: {
            export: "unsupported",
            import: "unsupported",
            slave: "available",
            master: "unsupported",
        },
        fmi2: {
            export: "unsupported",
            import: "unsupported",
            slave: "unsupported",
            master: "unsupported",
        },
        vendorId: "TWT",
    },
    {
        id: "VALDYN",
        displayName: "VALDYN",
        homepage: "http://www.ricardo.com/en-GB/What-we-do/Software/Products/VALDYN/",
        email: "undefined",
        note:
            'Multi-body dynamic and kinematic simulation for valvetrain, powertrain and transmission systems from <a href="http://www.ricardo.com/software">Ricardo Software</a>.',
        fmi1: {
            export: "unsupported",
            import: "unsupported",
            slave: "available",
            master: "unsupported",
        },
        fmi2: {
            export: "unsupported",
            import: "unsupported",
            slave: "available",
            master: "unsupported",
        },
        vendorId: "Ricardo",
    },
    {
        id: "Virtual_Engine",
        displayName: "Virtual Engine",
        homepage: "http://virtualengine.fev.com/",
        email: "virtualengine@fev.com",
        note:
            'Multibody dynamics simulation software for internal combustion engines, transmissions and their components from <a href="http://www.fev.com/">FEV</a>.',
        fmi1: {
            export: "unsupported",
            import: "unsupported",
            slave: "available",
            master: "available",
        },
        fmi2: {
            export: "unsupported",
            import: "unsupported",
            slave: "available",
            master: "available",
        },
        vendorId: "FEV",
    },
    {
        id: "WAVE_RT",
        displayName: "WAVE-RT",
        homepage: "http://www.ricardo.com/en-GB/What-we-do/Software/Products/WAVE-RT/",
        email: "undefined",
        note:
            'Real-time, crank-angle resolved engine simulation tool for testing new engine management systems in SiL, HiL, and rapid-prototyping from <a href="http://www.ricardo.com/software">Ricardo Software</a>.',
        fmi1: {
            export: "unsupported",
            import: "unsupported",
            slave: "available",
            master: "unsupported",
        },
        fmi2: {
            export: "unsupported",
            import: "unsupported",
            slave: "available",
            master: "unsupported",
        },
        vendorId: "Ricardo",
    },
    {
        id: "XFlow",
        displayName: "XFlow",
        homepage: "http://www.xflowcfd.com/",
        email: "undefined",
        note:
            "Computational Fluid Dynamics (CFD) code which uses a particle-based kinetic solver based on the Lattice-Boltzmann Method, thus avoids the meshing process and allows complex fluid-structure interaction including through FMI standard co-simulation.",
        fmi1: {
            export: "unsupported",
            import: "unsupported",
            slave: "available",
            master: "unsupported",
        },
        fmi2: {
            export: "unsupported",
            import: "unsupported",
            slave: "unsupported",
            master: "unsupported",
        },
        vendorId: "3DS",
    },
    {
        id: "agx_dynamics",
        displayName: "AGX Dynamics",
        homepage: "http://www.algoryx.se/products/agx-dynamics",
        email: "contact@algoryx.se",
        note:
            "AGX Dynamics is a professional multi-purpose physics engine for simulators, engineering, large scale granular simulators and more.",
        fmi1: {
            export: "unsupported",
            import: "unsupported",
            slave: "available",
            master: "unsupported",
        },
        fmi2: {
            export: "unsupported",
            import: "unsupported",
            slave: "available",
            master: "unsupported",
        },
        vendorId: "Algoryx",
    },
    {
        id: "dSPACE_SCALEXIO",
        displayName: "dSPACE SCALEXIO",
        homepage: "https://www.dspace.com/go/fmi",
        email: "undefined",
        note:
            'dSPACE SCALEXIO is a Hardware-in-the-Loop (HIL) integration and simulation platform from <a href="https://www.dspace.com">dSPACE</a>. Please also refer to the <a href="https://www.dspace.com/go/fmi">dSPACE FMI sites</a> for more information about the FMI 1.0 and FMI 2.0 support.',
        fmi1: {
            export: "unsupported",
            import: "unsupported",
            slave: "unsupported",
            master: "available",
        },
        fmi2: {
            export: "unsupported",
            import: "unsupported",
            slave: "unsupported",
            master: "available",
        },
        vendorId: "dSpace",
    },
    {
        id: "dSPACE_SYNECT",
        displayName: "dSPACE SYNECT",
        homepage: "https://www.dspace.com/go/fmi",
        email: "undefined",
        note:
            'dSPACE SYNECT is a data management tool from <a href="https://www.dspace.com">dSPACE</a> that enables you to manage FMUs and Simulink models as well as their dependencies, versions and variants throughout the entire software development process. Please also refer to the <a href="https://www.dspace.com/go/fmi">dSPACE FMI sites</a> for more information about the FMI support.',
        fmi1: {
            export: "unsupported",
            import: "unsupported",
            slave: "unsupported",
            master: "planned",
        },
        fmi2: {
            export: "unsupported",
            import: "unsupported",
            slave: "unsupported",
            master: "planned",
        },
        vendorId: "dSpace",
    },
    {
        id: "dSPACE_TargetLink",
        displayName: "dSPACE TargetLink",
        homepage: "https://www.dspace.com/go/fmi",
        email: "undefined",
        note:
            '<a href="https://www.dspace.com/en/pub/home/products/sw/pcgs/targetli.cfm">TargetLink</a> is a production code generator from <a href="https://www.dspace.com">dSPACE</a> that generates highly efficient C-code directly from Simulink/Stateflow models. Please also refer to the <a href="https://www.dspace.com/go/fmi">dSPACE FMI sites</a> for more information about the FMI support.',
        fmi1: {
            export: "unsupported",
            import: "unsupported",
            slave: "unsupported",
            master: "unsupported",
        },
        fmi2: {
            export: "unsupported",
            import: "unsupported",
            slave: "unsupported",
            master: "unsupported",
        },
        vendorId: "dSpace",
    },
    {
        id: "dSPACE_VEOS",
        displayName: "dSPACE VEOS",
        homepage: "https://www.dspace.com/go/fmi",
        email: "undefined",
        note:
            'dSPACE VEOS is a PC-based virtual integration and simulation platform from <a href="https://www.dspace.com">dSPACE</a>. Please also refer to the <a href="https://www.dspace.com/go/fmi">dSPACE FMI sites</a> for more information about the FMI 1.0 and FMI 2.0 support.',
        fmi1: {
            export: "unsupported",
            import: "unsupported",
            slave: "unsupported",
            master: "available",
        },
        fmi2: {
            export: "unsupported",
            import: "unsupported",
            slave: "unsupported",
            master: "available",
        },
        vendorId: "dSpace",
    },
    {
        id: "daetools",
        displayName: "DAE Tools",
        homepage: "http://www.daetools.com",
        email: "contact@daetools.com",
        note: "",
        fmi1: {
            export: "unsupported",
            import: "unsupported",
            slave: "unsupported",
            master: "unsupported",
        },
        fmi2: {
            export: "unsupported",
            import: "unsupported",
            slave: "unsupported",
            master: "unsupported",
        },
        vendorId: "daetools",
    },
    {
        id: "emtp",
        displayName: "EMTP-RV",
        homepage: "http://www.emtp-software.com",
        email: "e.rutovic@powersys-solutions.com",
        note:
            "EMTP-RV is a power system simulation tool. Version 3.4 or higher is required to use the FMI capabilities.",
        fmi1: {
            export: "unsupported",
            import: "unsupported",
            slave: "unsupported",
            master: "available",
        },
        fmi2: {
            export: "unsupported",
            import: "unsupported",
            slave: "unsupported",
            master: "available",
        },
        vendorId: "powersys",
    },
    {
        id: "mpcci",
        displayName: "MpCCI CouplingEnvironment",
        homepage: "http://www.mpcci.de",
        email: "undefined",
        note:
            'The <a href="http://www.mpcci.de">MpCCI CouplingEnvironment</a> from <a href="http://www.scai.fraunhofer.de/en/business-research-areas/multiphysics.html">Fraunhofer SCAI</a> is a vendor neutral interface for cosimulation in the 3D area',
        fmi1: {
            export: "unsupported",
            import: "unsupported",
            slave: "unsupported",
            master: "planned",
        },
        fmi2: {
            export: "unsupported",
            import: "unsupported",
            slave: "unsupported",
            master: "planned",
        },
        vendorId: "MpCCI",
    },
    {
        id: "optiSLang",
        displayName: "optiSLang",
        homepage: "https://www.dynardo.de/en/software/optislang.html",
        email: "support@dynardo.de",
        note:
            'optiSLang supports the export of Metamodels of optimal Prognosis (<a href="https://www.dynardo.de/en/software/optislang/mopcop.html">MOP</a>) as FMU.',
        fmi1: {
            export: "available",
            import: "planned",
            slave: "unsupported",
            master: "unsupported",
        },
        fmi2: {
            export: "available",
            import: "planned",
            slave: "unsupported",
            master: "unsupported",
        },
        vendorId: "Dynardo",
    },
    {
        id: "solidThinking_Activate",
        displayName: "solidThinking Activate",
        homepage: "http://www.altairhyperworks.com/product/solidThinking-Activate",
        email: "undefined",
        note: "Software environment for modeling, simulation and analysis of multi-disciplinary systems from Altair.",
        fmi1: {
            export: "unsupported",
            import: "available",
            slave: "unsupported",
            master: "available",
        },
        fmi2: {
            export: "unsupported",
            import: "available",
            slave: "unsupported",
            master: "available",
        },
        vendorId: "Altair",
    },
    {
        id: "trnsys_fmu",
        displayName: "TRNSYS FMU Export Utility",
        homepage: "http://trnsys-fmu.sourceforge.net",
        email: "ces@ait.ac.at",
        note: "A stand-alone tool for exporting FMUs for Co-Simulation from TRNSYS models.",
        fmi1: {
            export: "unsupported",
            import: "unsupported",
            slave: "available",
            master: "unsupported",
        },
        fmi2: {
            export: "unsupported",
            import: "unsupported",
            slave: "available",
            master: "unsupported",
        },
        vendorId: "widle",
    },
    {
        id: "xMOD",
        displayName: "xMOD",
        homepage: "http://www.xmodsoftware.com/",
        email: "undefined",
        note:
            'Heterogeneous model integration environment & virtual instrumentation and experimentation laboratory from <a href="http://www.ifpenergiesnouvelles.com/">IFPEN</a> distributed by <a href="http://www.d2t.com/">D2T</a>.',
        fmi1: {
            export: "unsupported",
            import: "available",
            slave: "unsupported",
            master: "available",
        },
        fmi2: {
            export: "unsupported",
            import: "available",
            slave: "unsupported",
            master: "available",
        },
        vendorId: "IFP",
    },
];
